version: 2
updates:
    -   package-ecosystem: 'github-actions'
        directory: '/'
        schedule:
            interval: 'weekly'
        assignees:
            - "Lopah"

    -   package-ecosystem: 'nuget'
        directory: '/'
        open-pull-requests-limit: 20
        schedule:
            interval: 'weekly'
        assignees:
            - "Lopah"
